<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Yanzhengma\Request\CheckCode instead.
     * @deprecated
     */
    class Request_CheckCode {}
}
class_exists(Request\CheckCode::class);
@trigger_error('Grpc\Yanzhengma\Request_CheckCode is deprecated and will be removed in the next major release. Use Grpc\Yanzhengma\Request\CheckCode instead', E_USER_DEPRECATED);

