<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Yanzhengma\Request\VerifyCode instead.
     * @deprecated
     */
    class Request_VerifyCode {}
}
class_exists(Request\VerifyCode::class);
@trigger_error('Grpc\Yanzhengma\Request_VerifyCode is deprecated and will be removed in the next major release. Use Grpc\Yanzhengma\Request\VerifyCode instead', E_USER_DEPRECATED);

