<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Yanzhengma\Response\CheckCode instead.
     * @deprecated
     */
    class Response_CheckCode {}
}
class_exists(Response\CheckCode::class);
@trigger_error('Grpc\Yanzhengma\Response_CheckCode is deprecated and will be removed in the next major release. Use Grpc\Yanzhengma\Response\CheckCode instead', E_USER_DEPRECATED);

