<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Yanzhengma\Response\VerifyCode instead.
     * @deprecated
     */
    class Response_VerifyCode {}
}
class_exists(Response\VerifyCode::class);
@trigger_error('Grpc\Yanzhengma\Response_VerifyCode is deprecated and will be removed in the next major release. Use Grpc\Yanzhengma\Response\VerifyCode instead', E_USER_DEPRECATED);

