<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 检查验证码是否有效
 *
 * Generated from protobuf message <code>Grpc.Yanzhengma.Response.CheckCode</code>
 */
class CheckCode extends \Google\Protobuf\Internal\Message
{
    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     */
    protected $result = null;
    /**
     *检查结果
     *
     * Generated from protobuf field <code>bool check_result = 2;</code>
     */
    protected $check_result = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Common\ResultMessage $result
     *           返回状态
     *     @type bool $check_result
     *          检查结果
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcYanzhengma::initOnce();
        parent::__construct($data);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @return \Grpc\Common\ResultMessage
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : null;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @param \Grpc\Common\ResultMessage $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Common\ResultMessage::class);
        $this->result = $var;

        return $this;
    }

    /**
     *检查结果
     *
     * Generated from protobuf field <code>bool check_result = 2;</code>
     * @return bool
     */
    public function getCheckResult()
    {
        return $this->check_result;
    }

    /**
     *检查结果
     *
     * Generated from protobuf field <code>bool check_result = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCheckResult($var)
    {
        GPBUtil::checkBool($var);
        $this->check_result = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CheckCode::class, \Grpc\Yanzhengma\Response_CheckCode::class);

