<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 验证码
 *
 * Generated from protobuf message <code>Grpc.Yanzhengma.Response.VerifyCode</code>
 */
class VerifyCode extends \Google\Protobuf\Internal\Message
{
    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     */
    protected $result = null;
    /**
     * 验证码二进制数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';
    /**
     * 验证码的 mine类型
     *
     * Generated from protobuf field <code>string mine = 3;</code>
     */
    protected $mine = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Common\ResultMessage $result
     *           返回状态
     *     @type string $data
     *           验证码二进制数据
     *     @type string $mine
     *           验证码的 mine类型
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcYanzhengma::initOnce();
        parent::__construct($data);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @return \Grpc\Common\ResultMessage
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : null;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @param \Grpc\Common\ResultMessage $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Common\ResultMessage::class);
        $this->result = $var;

        return $this;
    }

    /**
     * 验证码二进制数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * 验证码二进制数据
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * 验证码的 mine类型
     *
     * Generated from protobuf field <code>string mine = 3;</code>
     * @return string
     */
    public function getMine()
    {
        return $this->mine;
    }

    /**
     * 验证码的 mine类型
     *
     * Generated from protobuf field <code>string mine = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMine($var)
    {
        GPBUtil::checkString($var, True);
        $this->mine = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(VerifyCode::class, \Grpc\Yanzhengma\Response_VerifyCode::class);

