<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpccommon.proto

namespace Grpc\Common;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Common\ResultMessage\ResultCode instead.
     * @deprecated
     */
    class ResultMessage_ResultCode {}
}
class_exists(ResultMessage\ResultCode::class);
@trigger_error('Grpc\Common\ResultMessage_ResultCode is deprecated and will be removed in the next major release. Use Grpc\Common\ResultMessage\ResultCode instead', E_USER_DEPRECATED);

