version: '2'
services:
  dev:
    build: .
    image: yingchaoyanzhengma:dev
    privileged: false
    restart: unless-stopped
    ports:
    - 32308:9502
    - 32309:80
    volumes:
    - .:/var/www/html
    tty: true
    command: /bin/bash