<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 查询用户列表
 *
 * Generated from protobuf message <code>Grpc.User.Response.Login</code>
 */
class Login extends \Google\Protobuf\Internal\Message
{
    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     */
    protected $result = null;
    /**
     * 登陆的用户
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserInfo user = 2;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Common\ResultMessage $result
     *           返回状态
     *     @type \Grpc\User\Common\UserInfo $user
     *           登陆的用户
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcuser::initOnce();
        parent::__construct($data);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @return \Grpc\Common\ResultMessage
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : null;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * 返回状态
     *
     * Generated from protobuf field <code>.Grpc.Common.ResultMessage result = 1;</code>
     * @param \Grpc\Common\ResultMessage $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Common\ResultMessage::class);
        $this->result = $var;

        return $this;
    }

    /**
     * 登陆的用户
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserInfo user = 2;</code>
     * @return \Grpc\User\Common\UserInfo
     */
    public function getUser()
    {
        return isset($this->user) ? $this->user : null;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * 登陆的用户
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserInfo user = 2;</code>
     * @param \Grpc\User\Common\UserInfo $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Grpc\User\Common\UserInfo::class);
        $this->user = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Login::class, \Grpc\User\Response_Login::class);

