<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcsms.proto

namespace Grpc\Sms\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *查找用户列表
 *
 * Generated from protobuf message <code>Grpc.Sms.Request.SendVerify</code>
 */
class SendVerify extends \Google\Protobuf\Internal\Message
{
    /**
     * 发送验证码的手机
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    protected $phone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone
     *           发送验证码的手机
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcsms::initOnce();
        parent::__construct($data);
    }

    /**
     * 发送验证码的手机
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * 发送验证码的手机
     *
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SendVerify::class, \Grpc\Sms\Request_SendVerify::class);

