<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Common\UserInfo instead.
     * @deprecated
     */
    class Common_UserInfo {}
}
class_exists(Common\UserInfo::class);
@trigger_error('Grpc\User\Common_UserInfo is deprecated and will be removed in the next major release. Use Grpc\User\Common\UserInfo instead', E_USER_DEPRECATED);

