<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Common\UserAccInfo instead.
     * @deprecated
     */
    class Common_UserAccInfo {}
}
class_exists(Common\UserAccInfo::class);
@trigger_error('Grpc\User\Common_UserAccInfo is deprecated and will be removed in the next major release. Use Grpc\User\Common\UserAccInfo instead', E_USER_DEPRECATED);

