<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Common\UserInfoCate instead.
     * @deprecated
     */
    class Common_UserInfoCate {}
}
class_exists(Common\UserInfoCate::class);
@trigger_error('Grpc\User\Common_UserInfoCate is deprecated and will be removed in the next major release. Use Grpc\User\Common\UserInfoCate instead', E_USER_DEPRECATED);

