<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Common\UserExtInfo instead.
     * @deprecated
     */
    class Common_UserExtInfo {}
}
class_exists(Common\UserExtInfo::class);
@trigger_error('Grpc\User\Common_UserExtInfo is deprecated and will be removed in the next major release. Use Grpc\User\Common\UserExtInfo instead', E_USER_DEPRECATED);

