<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Request\QueryUList instead.
     * @deprecated
     */
    class Request_QueryUList {}
}
class_exists(Request\QueryUList::class);
@trigger_error('Grpc\User\Request_QueryUList is deprecated and will be removed in the next major release. Use Grpc\User\Request\QueryUList instead', E_USER_DEPRECATED);

