<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Request\QUserInfo instead.
     * @deprecated
     */
    class Request_QUserInfo {}
}
class_exists(Request\QUserInfo::class);
@trigger_error('Grpc\User\Request_QUserInfo is deprecated and will be removed in the next major release. Use Grpc\User\Request\QUserInfo instead', E_USER_DEPRECATED);

