<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Request\UserLogin instead.
     * @deprecated
     */
    class Request_UserLogin {}
}
class_exists(Request\UserLogin::class);
@trigger_error('Grpc\User\Request_UserLogin is deprecated and will be removed in the next major release. Use Grpc\User\Request\UserLogin instead', E_USER_DEPRECATED);

