<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Response\Login instead.
     * @deprecated
     */
    class Response_Login {}
}
class_exists(Response\Login::class);
@trigger_error('Grpc\User\Response_Login is deprecated and will be removed in the next major release. Use Grpc\User\Response\Login instead', E_USER_DEPRECATED);

