<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Response\QueryUList instead.
     * @deprecated
     */
    class Response_QueryUList {}
}
class_exists(Response\QueryUList::class);
@trigger_error('Grpc\User\Response_QueryUList is deprecated and will be removed in the next major release. Use Grpc\User\Response\QueryUList instead', E_USER_DEPRECATED);

