<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User;

if (false) {
    /**
     * This class is deprecated. Use Grpc\User\Response\QUserInfo instead.
     * @deprecated
     */
    class Response_QUserInfo {}
}
class_exists(Response\QUserInfo::class);
@trigger_error('Grpc\User\Response_QUserInfo is deprecated and will be removed in the next major release. Use Grpc\User\Response\QUserInfo instead', E_USER_DEPRECATED);

