<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcYanzhengma.proto

namespace Grpc\Yanzhengma\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 检查验证码是否有效
 *
 * Generated from protobuf message <code>Grpc.Yanzhengma.Request.CheckCode</code>
 */
class CheckCode extends \Google\Protobuf\Internal\Message
{
    /**
     * 验证码的标识
     *
     * Generated from protobuf field <code>string sk = 1;</code>
     */
    protected $sk = '';
    /**
     * 验证码的内容
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sk
     *           验证码的标识
     *     @type string $code
     *           验证码的内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcYanzhengma::initOnce();
        parent::__construct($data);
    }

    /**
     * 验证码的标识
     *
     * Generated from protobuf field <code>string sk = 1;</code>
     * @return string
     */
    public function getSk()
    {
        return $this->sk;
    }

    /**
     * 验证码的标识
     *
     * Generated from protobuf field <code>string sk = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSk($var)
    {
        GPBUtil::checkString($var, True);
        $this->sk = $var;

        return $this;
    }

    /**
     * 验证码的内容
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 验证码的内容
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CheckCode::class, \Grpc\Yanzhengma\Request_CheckCode::class);

