<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户聊天系统信息
 *
 * Generated from protobuf message <code>Grpc.User.Common.UserExtInfo</code>
 */
class UserExtInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户uid
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * 昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    protected $nickname = '';
    /**
     * 个性签名
     *
     * Generated from protobuf field <code>string personal = 3;</code>
     */
    protected $personal = '';
    /**
     * 生日
     *
     * Generated from protobuf field <code>int64 birthday = 4;</code>
     */
    protected $birthday = 0;
    /**
     * 头像
     *
     * Generated from protobuf field <code>string profile_picture = 5;</code>
     */
    protected $profile_picture = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *           用户uid
     *     @type string $nickname
     *           昵称
     *     @type string $personal
     *           个性签名
     *     @type int|string $birthday
     *           生日
     *     @type string $profile_picture
     *           头像
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcuser::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户uid
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户uid
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * 个性签名
     *
     * Generated from protobuf field <code>string personal = 3;</code>
     * @return string
     */
    public function getPersonal()
    {
        return $this->personal;
    }

    /**
     * 个性签名
     *
     * Generated from protobuf field <code>string personal = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPersonal($var)
    {
        GPBUtil::checkString($var, True);
        $this->personal = $var;

        return $this;
    }

    /**
     * 生日
     *
     * Generated from protobuf field <code>int64 birthday = 4;</code>
     * @return int|string
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * 生日
     *
     * Generated from protobuf field <code>int64 birthday = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBirthday($var)
    {
        GPBUtil::checkInt64($var);
        $this->birthday = $var;

        return $this;
    }

    /**
     * 头像
     *
     * Generated from protobuf field <code>string profile_picture = 5;</code>
     * @return string
     */
    public function getProfilePicture()
    {
        return $this->profile_picture;
    }

    /**
     * 头像
     *
     * Generated from protobuf field <code>string profile_picture = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProfilePicture($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_picture = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserExtInfo::class, \Grpc\User\Common_UserExtInfo::class);

