<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户账户信息
 *
 * Generated from protobuf message <code>Grpc.User.Common.UserAccInfo</code>
 */
class UserAccInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户名
     *
     * Generated from protobuf field <code>string username = 1;</code>
     */
    protected $username = '';
    /**
     * 最后登陆时间
     *
     * Generated from protobuf field <code>int64 last_login_time = 2;</code>
     */
    protected $last_login_time = 0;
    /**
     * 是否开启谷歌身份 验证器
     *
     * Generated from protobuf field <code>bool open_goole_auth = 3;</code>
     */
    protected $open_goole_auth = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *           用户名
     *     @type int|string $last_login_time
     *           最后登陆时间
     *     @type bool $open_goole_auth
     *           是否开启谷歌身份 验证器
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcuser::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户名
     *
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * 用户名
     *
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * 最后登陆时间
     *
     * Generated from protobuf field <code>int64 last_login_time = 2;</code>
     * @return int|string
     */
    public function getLastLoginTime()
    {
        return $this->last_login_time;
    }

    /**
     * 最后登陆时间
     *
     * Generated from protobuf field <code>int64 last_login_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_login_time = $var;

        return $this;
    }

    /**
     * 是否开启谷歌身份 验证器
     *
     * Generated from protobuf field <code>bool open_goole_auth = 3;</code>
     * @return bool
     */
    public function getOpenGooleAuth()
    {
        return $this->open_goole_auth;
    }

    /**
     * 是否开启谷歌身份 验证器
     *
     * Generated from protobuf field <code>bool open_goole_auth = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOpenGooleAuth($var)
    {
        GPBUtil::checkBool($var);
        $this->open_goole_auth = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserAccInfo::class, \Grpc\User\Common_UserAccInfo::class);

