<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Common;

use UnexpectedValueException;

/**
 *用户信息分类
 *
 * Protobuf type <code>Grpc.User.Common.UserInfoCate</code>
 */
class UserInfoCate
{
    /**
     * Generated from protobuf enum <code>ACC = 0;</code>
     */
    const ACC = 0;
    /**
     * Generated from protobuf enum <code>EXT = 1;</code>
     */
    const EXT = 1;

    private static $valueToName = [
        self::ACC => 'ACC',
        self::EXT => 'EXT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserInfoCate::class, \Grpc\User\Common_UserInfoCate::class);

