<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户信息
 *
 * Generated from protobuf message <code>Grpc.User.Common.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     */
    protected $uin = 0;
    /**
     *用户账户信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserAccInfo acc = 2;</code>
     */
    protected $acc = null;
    /**
     * 用户扩展信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserExtInfo ext = 3;</code>
     */
    protected $ext = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uin
     *           用户uin
     *     @type \Grpc\User\Common\UserAccInfo $acc
     *          用户账户信息
     *     @type \Grpc\User\Common\UserExtInfo $ext
     *           用户扩展信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcuser::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     * @return int|string
     */
    public function getUin()
    {
        return $this->uin;
    }

    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUin($var)
    {
        GPBUtil::checkInt64($var);
        $this->uin = $var;

        return $this;
    }

    /**
     *用户账户信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserAccInfo acc = 2;</code>
     * @return \Grpc\User\Common\UserAccInfo
     */
    public function getAcc()
    {
        return isset($this->acc) ? $this->acc : null;
    }

    public function hasAcc()
    {
        return isset($this->acc);
    }

    public function clearAcc()
    {
        unset($this->acc);
    }

    /**
     *用户账户信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserAccInfo acc = 2;</code>
     * @param \Grpc\User\Common\UserAccInfo $var
     * @return $this
     */
    public function setAcc($var)
    {
        GPBUtil::checkMessage($var, \Grpc\User\Common\UserAccInfo::class);
        $this->acc = $var;

        return $this;
    }

    /**
     * 用户扩展信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserExtInfo ext = 3;</code>
     * @return \Grpc\User\Common\UserExtInfo
     */
    public function getExt()
    {
        return isset($this->ext) ? $this->ext : null;
    }

    public function hasExt()
    {
        return isset($this->ext);
    }

    public function clearExt()
    {
        unset($this->ext);
    }

    /**
     * 用户扩展信息
     *
     * Generated from protobuf field <code>.Grpc.User.Common.UserExtInfo ext = 3;</code>
     * @param \Grpc\User\Common\UserExtInfo $var
     * @return $this
     */
    public function setExt($var)
    {
        GPBUtil::checkMessage($var, \Grpc\User\Common\UserExtInfo::class);
        $this->ext = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserInfo::class, \Grpc\User\Common_UserInfo::class);

