<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcsms.proto

namespace Grpc\Sms;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Sms\Request\SendVerify\TypeCate instead.
     * @deprecated
     */
    class Request_SendVerify_TypeCate {}
}
class_exists(Request\SendVerify\TypeCate::class);
@trigger_error('Grpc\Sms\Request_SendVerify_TypeCate is deprecated and will be removed in the next major release. Use Grpc\Sms\Request\SendVerify\TypeCate instead', E_USER_DEPRECATED);

