<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcsms.proto

namespace Grpc\Sms;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *请求信息
 *
 * Generated from protobuf message <code>Grpc.Sms.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcsms::initOnce();
        parent::__construct($data);
    }

}

