<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcsms.proto

namespace Grpc\Sms;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Sms\Response\SendVerify instead.
     * @deprecated
     */
    class Response_SendVerify {}
}
class_exists(Response\SendVerify::class);
@trigger_error('Grpc\Sms\Response_SendVerify is deprecated and will be removed in the next major release. Use Grpc\Sms\Response\SendVerify instead', E_USER_DEPRECATED);

