<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcuser.proto

namespace Grpc\User\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 查询单条用户
 *
 * Generated from protobuf message <code>Grpc.User.Request.QUserInfo</code>
 */
class QUserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     */
    protected $uin = 0;
    /**
     *需要那些信息
     *
     * Generated from protobuf field <code>repeated .Grpc.User.Common.UserInfoCate cate = 2;</code>
     */
    private $cate;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uin
     *           用户uin
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $cate
     *          需要那些信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpcuser::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     * @return int|string
     */
    public function getUin()
    {
        return $this->uin;
    }

    /**
     * 用户uin
     *
     * Generated from protobuf field <code>int64 uin = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUin($var)
    {
        GPBUtil::checkInt64($var);
        $this->uin = $var;

        return $this;
    }

    /**
     *需要那些信息
     *
     * Generated from protobuf field <code>repeated .Grpc.User.Common.UserInfoCate cate = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCate()
    {
        return $this->cate;
    }

    /**
     *需要那些信息
     *
     * Generated from protobuf field <code>repeated .Grpc.User.Common.UserInfoCate cate = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Grpc\User\Common\UserInfoCate::class);
        $this->cate = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(QUserInfo::class, \Grpc\User\Request_QUserInfo::class);

